DROP TABLE IF EXISTS "os";
DROP TABLE IF EXISTS "bin";
DROP TABLE IF EXISTS "bin_os_id";
DROP TABLE IF EXISTS "pair";
DROP TABLE IF EXISTS "pair_binary_id";

CREATE TABLE "os" ("id" INTEGER NOT NULL PRIMARY KEY, "build" VARCHAR(255) NOT NULL, "name" VARCHAR(255) NOT NULL, "ver" VARCHAR(255) NOT NULL, "path" TEXT NOT NULL);
CREATE TABLE "bin" ("id" INTEGER NOT NULL PRIMARY KEY, "os_id" INTEGER NOT NULL, "path" TEXT NOT NULL, "xml" TEXT NOT NULL, "json" TEXT NOT NULL, FOREIGN KEY ("os_id") REFERENCES "os" ("id"));
CREATE INDEX "bin_os_id" ON "bin" ("os_id");
CREATE TABLE "pair" ("id" INTEGER NOT NULL PRIMARY KEY, "binary_id" INTEGER NOT NULL, "key" VARCHAR(255) NOT NULL, "value" TEXT NOT NULL, FOREIGN KEY ("binary_id") REFERENCES "bin" ("id"));
CREATE INDEX "pair_binary_id" ON "pair" ("binary_id");