[project]
name = "unwrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyhpke>=0.6.2",
    "requests>=2.32.5",
]

[tool.ruff]
extend-exclude = ["aeota"]
